name: weather_api
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  animated_rotating_widget: ^0.0.2
  animated_splash_screen: ^1.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  http: ^1.1.0
  intl: ^0.18.1
  loading_animation_widget: ^1.2.0+4
  lottie: ^2.6.0
  supabase_flutter: ^1.10.14
  weather_icons: ^3.0.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/icons/
    - assets/bg/
